package com.family.tree.dynamoDB.table.mapping;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGenerateStrategy;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedDefault;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedTimestamp;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;

@DynamoDBTable(tableName="FamilyTreeTable5")
public class FamilyTreeTablePOJO {
	
	//Hash key and sort key
	@DynamoDBHashKey(attributeName = "UserId")
	private String userId;
	
	//sort key is also gsi-relationship-index key
	@DynamoDBRangeKey(attributeName = "Relationship")
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "relationShip-gsi")
	private String relationship;
	
	//attributes on the table
	@DynamoDBAttribute(attributeName = "First Name")
	private String firstName;
	@DynamoDBAttribute(attributeName = "Last Name")
	private String lastName;
	@DynamoDBAttribute(attributeName = "Gender")
	private String gender;//can be enum and converted to String(use dynamodbconverter)
	@DynamoDBAttribute(attributeName = "DOB")
	private String dob; // can be java8 datetime-use dynamodbconverter to convert to string
	@DynamoDBAttribute(attributeName = "Age")
	private String age; //calculated based on DOB
	@DynamoDBAttribute(attributeName = "Address")
	private Address address; //should be Address type and get it converted - spike
	@DynamoDBAutoGeneratedDefault("Living")
	@DynamoDBAttribute(attributeName = "Status")
	private String status; // can be enum living or deceased
	@DynamoDBAttribute(attributeName = "BirthPlace")
	private String birthPlace;
	@DynamoDBAttribute(attributeName = "PhoneNumber")
	private String phoneNumber;
	@DynamoDBAttribute(attributeName = "LastUpdatedDateTime")
	@DynamoDBTypeConvertedTimestamp(pattern="yyyyMMddHHmmssSSS", timeZone="UTC")
	@DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
	private Date lastUpdatedDateTime;

	//GSI keys
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "childrenKey-gsi", attributeName = "ChildrenKey")
	private String childrenkey;
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "spouseKey-gsi", attributeName = "SpouseKey")
	private String spousekey;
	
	@DynamoDBHashKey
	public String getUserId() {
		return userId;
	}
	
	public void setUserId(String userId) {
		this.userId = userId;
	}
	
	public String getRelationship() {
		return relationship;
	}
	
	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}
	
	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getGender() {
		return gender;
	}
	
	public void setGender(String gender) {
		this.gender = gender;
	}
	
	public String getDob() {
		return dob;
	}
	
	public void setDob(String dob) {
		this.dob = dob;
	}
	
	public String getAge() {
		return age;
	}
	
	public void setAge(String age) {
		this.age = age;
	}
	
	public Address getAddress() {
		return address;
	}
	
	public void setAddress(Address address) {
		this.address = address;
	}
	
	public String getStatus() {
		return status;
	}
	
	public void setStatus(String status) {
		this.status = status;
	}
	
	public String getBirthPlace() {
		return birthPlace;
	}
	
	public void setBirthPlace(String birthPlace) {
		this.birthPlace = birthPlace;
	}
	
	public String getPhoneNumber() {
		return phoneNumber;
	}
	
	public void setPhoneNumber(String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}
	
	public String getChildrenkey() {
		return childrenkey;
	}
	
	public void setChildrenkey(String childrenkey) {
		this.childrenkey = childrenkey;
	}
	
	public String getSpousekey() {
		return spousekey;
	}
	
	public void setSpousekey(String spousekey) {
		this.spousekey = spousekey;
	}
	
	public Date getLastUpdatedDateTime() {
		return lastUpdatedDateTime;
	}

	public void setLastUpdatedDateTime(Date lastUpdatedDateTime) {
		this.lastUpdatedDateTime = lastUpdatedDateTime;
	}
}
